name: SpawnPlugin
version: '${project.version}'
main: dev.cosmics.hardcoreplugin.HardcorePlugin
api-version: 1.19
libraries:
  - "dev.dejvokep:boosted-yaml:1.3.1"
commands:
  setspawn:
    description: "Sets the spawn point of the server"
  delspawn:
    description: "Deletes the spawn point of the server"
  spawn:
    description: "Teleports you to the spawn point of the server"